server:
  port: 8085

spring:
  application:
    name: service-litiges

  datasource:
    url: jdbc:postgresql://localhost:5445/${POSTGRES_LITIGES_DB:db_litiges}
    username: ${POSTGRES_LITIGES_USER}
    password: ${POSTGRES_LITIGES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 60000
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_VHOST}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

serviloc:
  internal-token: ${INTERNAL_TOKEN}