server:
  port: 8085

spring:
  application:
    name: service-litiges

  datasource:
    url: jdbc:postgresql://${DB_LITIGES_HOST}:${DB_LITIGES_PORT}/${DB_LITIGES_NAME}
    username: ${DB_LITIGES_USER}
    password: ${DB_LITIGES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_VHOST}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME}:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

serviloc:
  internal-token: ${INTERNAL_TOKEN}