server:
  port: 8083

spring:
  application:
    name: service-negociations

  datasource:
    url: jdbc:postgresql://localhost:5443/${POSTGRES_NEGO_DB:db_negociations}
    username: ${POSTGRES_NEGO_USER:svc_negociations}
    password: ${POSTGRES_NEGO_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_VHOST:/}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.serviloc: DEBUG
    org.springframework.amqp: INFO