server:
  port: 8083

spring:
  application:
    name: service-negociations

  datasource:
    url: jdbc:postgresql://localhost:5443/${POSTGRES_NEGO_DB:db_negociations}
    username: ${POSTGRES_NEGO_USER:svc_negociations}
    password: ${POSTGRES_NEGO_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 60000
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_VHOST:/}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

internal:
  token: ${INTERNAL_TOKEN}

websocket:
  stomp-relay:
    host: ${RABBITMQ_HOST:localhost}
    port: 61613
    client-login: ${RABBITMQ_DEFAULT_USER:admin}
    client-passcode: ${RABBITMQ_DEFAULT_PASS}

logging:
  level:
    com.serviloc: DEBUG
    org.springframework.amqp: INFO