server:
  port: 8087

spring:
  application:
    name: service-categories

  profiles:
    active: docker

  datasource:
    url: jdbc:postgresql://${DB_HOST:svc-categories-db}:${DB_PORT:5432}/${DB_NAME:db_categories}
    username: ${DB_USER:serviloc}
    password: ${DB_PASSWORD:serviloc}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Africa/Douala
    show-sql: false

  sql:
    init:
      mode: always
      continue-on-error: true

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 5
          multiplier: 2.0

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1h en ms
      cache-null-values: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

serviloc:
  internal-token: ${INTERNAL_TOKEN}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.serviloc.categories: INFO
