server:
  port: 8087

spring:
  application:
    name: service-categories

  profiles:
    active: docker

  datasource:
    url: jdbc:postgresql://localhost:5447/${POSTGRES_CATEGORIES_DB:db_categories}
    username: ${POSTGRES_CATEGORIES_USER}
    password: ${POSTGRES_CATEGORIES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Africa/Douala
    show-sql: false

  sql:
    init:
      mode: always
      continue-on-error: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 5
          multiplier: 2.0

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1h en ms
      cache-null-values: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

serviloc:
  internal-token: ${INTERNAL_TOKEN}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.serviloc.categories: INFO
