server:
  port: ${SERVER_PORT:8087}

spring:
  application:
    name: service-categories
  profiles:
    active: ${SPRING_PROFILE:local}

# =========================
# Profil LOCAL
# =========================
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5447/${POSTGRES_CATEGORIES_DB:db_categories}
    username: ${POSTGRES_CATEGORIES_USER:svc_categories}
    password: ${POSTGRES_CATEGORIES_PASSWORD:categories_pass_2026}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# =========================
# Profil DOCKER
# =========================
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://serviloc-db-categories:5432/${POSTGRES_CATEGORIES_DB:db_categories}
    username: ${POSTGRES_CATEGORIES_USER:svc_categories}
    password: ${POSTGRES_CATEGORIES_PASSWORD:categories_pass_2026}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Désactivation de la sécurité JWT en mode Docker
  security:
    enabled: false

# =========================
# Profil TEST
# =========================
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 0

# =========================
# Config commune (Redis, Eureka, RabbitMQ, Logging, Swagger)
# =========================
---
spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redis123}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
  instance:
    prefer-ip-address: true

rabbitmq:
  host: ${RABBITMQ_HOST:rabbitmq}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USER:svc_categories}
  password: ${RABBITMQ_PASS:categories_pass_2026}
  virtual-host: ${RABBITMQ_VHOST:/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: ${LOG_SQL_LEVEL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_BINDER_LEVEL:TRACE}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha

