server:
  port: 8088
  servlet:
    context-path: /api/files

spring:
  application:
    name: file-service

  datasource:
    url: jdbc:postgresql://db-media:5432/filesdb
    username: svc_media
    password: svc_media
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME}:8761/eureka/
  instance:
    prefer-ip-address: true

minio:
  url: http://minio:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: ${MINIO_BUCKET}

redis:
  host: redis
  port: 6379

rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest

security:
  internal-token: ${INTERNAL_TOKEN}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

